apiVersion: apps/v1
kind: Deployment
metadata:
  name: <whatever you want to call your deployment>
  labels:
    <any key>: <any value>
spec:
  replicas: <however many number of replica of pods you want>
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.0
        ports:
        - containerPort: 80